name: Deploy to Oracle Khanh Digital

on:
  push:
    branches: [master]

jobs:
  publish-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout GitHub actions
      uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish -c Release -o publish
    # - name: Install zip
    #   uses: montudor/action-zip@v1
    # - name: Zip output
    #   run: zip -qq -r horizon.zip publish

    - name: Rename web.config to _web.config to stop app.
      shell: python
      run: |
        import ftplib
        ftp = ftplib.FTP('${{ secrets.FTP_SERVER }}')
        ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')
        ftp.rename('web.config', '_web.config')
        ftp.quit()

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./publish/

    - name: Rename _web.config back to web.config to start app.
      shell: python
      run: |
        import ftplib
        ftp = ftplib.FTP('${{ secrets.FTP_SERVER }}')
        ftp.login('${{ secrets.FTP_USERNAME }}', '${{ secrets.FTP_PASSWORD }}')
        ftp.rename('_web.config', 'web.config')
        ftp.quit()
